apiVersion: v1
kind: Pod
metadata:
  name: lls-ollama
spec:
  hostNetwork: false # only Llama Stack container should be exposed
  containers:
    - name: ollama
      image: ollama/ollama
      ports:
        - containerPort: 11435
      volumeMounts:
        - mountPath: /root/.ollama:Z
          name: ollama-volume
      resources:
        limits:
          nvidia.com/gpu=all: 1
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: OLLAMA_HOST
          value: "0.0.0.0:11435"
    - name: llama-stack
      image: ramalama/llama-stack
      command: ["/usr/bin/entrypoint.sh"]
      args:
        - llama
        - stack
        - run
        - /tmp/ollama-run.yaml
      ports:
        - containerPort: 8321
        - hostPort: 8321
      volumeMounts:
        - mountPath: /tmp/ollama-run.yaml:Z
          name: lls-volume
      env:
        - name: INFERENCE_MODEL
          value: "llama3.2:latest"
        - name: OLLAMA_URL
          value: "0.0.0.0:11435"
  volumes:
    - name: ollama-volume
      hostPath:
        path: /home/instructlab/.ollama
        type: Directory
    - name: lls-volume
      hostPath:
        path: /home/instructlab/.llama/distributions/ollama/ollama-run.yaml
        type: File
